# linux-dex

theme[main_bg]="#1E1E2E"
theme[main_fg]="#CDD6F4"

theme[title]="#7EC8FF"
theme[hi_fg]="#FFFFFF"

theme[selected_bg]="#313244"
theme[selected_fg]="#CDD6F4"

theme[inactive_fg]="#5C6180"

theme[graph_text]="#CDD6F4"
theme[meter_bg]="#313244"

theme[proc_misc]="#7DE1D0"

theme[cpu_box]="#4C7CFF"
theme[mem_box]="#7DE1D0"
theme[net_box]="#7EC8FF"
theme[proc_box]="#B49AFF"

theme[div_line]="#5C6180"

theme[temp_start]="#7DE1D0"
theme[temp_mid]="#7EC8FF"
theme[temp_end]="#C4A7FF"

theme[cpu_start]="#4C7CFF"
theme[cpu_mid]="#7EC8FF"
theme[cpu_end]="#B49AFF"

theme[free_start]="#7DE1D0"
theme[free_mid]="#5AD1E6"
theme[free_end]="#7EC8FF"

theme[cached_start]="#5AD1E6"
theme[cached_mid]="#7EC8FF"
theme[cached_end]="#B49AFF"

theme[available_start]="#7DE1D0"
theme[available_mid]="#7EC8FF"
theme[available_end]="#C4A7FF"

theme[used_start]="#C4A7FF"
theme[used_mid]="#B49AFF"
theme[used_end]="#7EC8FF"

theme[download_start]="#7DE1D0"
theme[download_mid]="#5AD1E6"
theme[download_end]="#7EC8FF"

theme[upload_start]="#C4A7FF"
theme[upload_mid]="#B49AFF"
theme[upload_end]="#7EC8FF"

theme[process_start]="#7DE1D0"
theme[process_mid]="#7EC8FF"
theme[process_end]="#C4A7FF"

